name: music_learning_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.0.11
  video_player: ^2.5.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^4.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0  # Added for Hive Flutter integration
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  provider: ^6.1.2
  dio: ^5.8.0
  pretty_dio_logger: ^1.3.1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.4
  mocktail: ^1.0.4
  test_cov_console: ^0.2.2
  fftea: ^1.5.0+1
  flutter_sound: ^9.24.4
  sensors_plus: 6.0.0
  youtube_player_iframe: ^4.0.4
  webview_flutter: ^4.9.0
  connectivity_plus: ^5.0.2
  fluentui_system_icons: ^1.1.223
  pitch_detector_dart: ^0.0.7
  flutter_audio_capture: ^1.1.6
  syncfusion_flutter_gauges: ^21.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/